language: c

services:
  - docker

stages:
  - "build only"

jobs:
  include:
    - stage: "build only"
      name: "alpine"
      script:
        - docker build -t alpine -f docker/Dockerfile.alpine .
        - docker run alpine -- dune exec docker/test_docker.ml alpine
    - stage: "build only"
      name: "debian"
      script:
        - docker build -t debian -f docker/Dockerfile.debian .
        - docker run debian -- dune exec docker/test_docker.ml debian
    - stage: "build only"
      name: "fedora"
      script:
        - docker build -t fedora -f docker/Dockerfile.fedora .
        - docker run fedora -- dune exec docker/test_docker.ml fedora
    - stage: "build only"
      name: "opensuse"
      script:
        - docker build -t opensuse -f docker/Dockerfile.opensuse .
        - docker run opensuse -- dune exec docker/test_docker.ml opensuse
    - stage: "build only"
      name: "ubuntu"
      script:
        - docker build -t ubuntu -f docker/Dockerfile.ubuntu .
        - docker run ubuntu -- dune exec docker/test_docker.ml ubuntu
    # - stage: "build only"
    #   name: "ubuntu.arm"
    #   script:
    #     - docker build -t ubuntu_arm -f docker/Dockerfile.ubuntu.arm .
    #     - docker run arm -- dune exec docker/test_docker.ml arm
