language: c

services:
  - docker

install:
  - docker build -f docker/Dockerfile.alpine .
  - docker build -f docker/Dockerfile.debian .
  - docker build -f docker/Dockerfile.fedora .
  - docker build -f docker/Dockerfile.opensuse .
  - docker build -f docker/Dockerfile.ubuntu .
  - docker build -f docker/Dockerfile.ubuntu.arm .

script:
  - docker images
