language: c

services:
  - docker

jobs:
  include:
    - script: docker build -f docker/Dockerfile.alpine .
    - script: docker build -f docker/Dockerfile.debian .
    - script: docker build -f docker/Dockerfile.fedora .
    - script: docker build -f docker/Dockerfile.opensuse .
    - script: docker build -f docker/Dockerfile.ubuntu .
    - script: docker build -f docker/Dockerfile.ubuntu.arm .
    - stage: check
      script: docker images
